packages:
  - 'packages/*/*'
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@deepseek-ai/dsh-brand@0.1.5-rc.1'
  - '@deepseek-ai/dsh-client-connection@0.1.5-rc.1'
  - '@deepseek-ai/dsh-client-locale@0.1.5-rc.1'
  - '@deepseek-ai/dsh-client-ui-theme@0.1.5-rc.1'
  - '@deepseek-ai/dsh-credentials@0.1.5-rc.1'
  - '@deepseek-ai/dsh-invariants@0.1.5-rc.1'
  - '@deepseek-ai/dsh-llm@0.1.5-rc.1'
  - '@deepseek-ai/dsh-storage-domain@0.1.5-rc.1'
  - '@deepseek-ai/dsh-storage-json@0.1.5-rc.1'
  - '@deepseek-ai/dsh-storage@0.1.5-rc.1'
  - '@deepseek-ai/dsh-timeout@0.1.5-rc.1'
  - '@deepseek-ai/dsh-typert-protocol@0.1.5-rc.1'
  - '@deepseek-ai/dsh-util-crypto@0.1.5-rc.1'
  - '@deepseek-ai/dsh-util-values@0.1.5-rc.1'
